IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO-MESSAGE.

DATA DIVISION.
   LINKAGE SECTION.
   01 RETURNED-MESSAGE PIC A(30).
   01 USER-NAME PIC A(15).

PROCEDURE DIVISION USING RETURNED-MESSAGE, USER-NAME.
  MOVE SPACES TO RETURNED-MESSAGE.
  IF USER-NAME = SPACES THEN
    MOVE 'world' to USER-NAME.
  STRING
    'Hello, ' DELIMITED BY SIZE
    USER-NAME DELIMITED BY SPACES
    '!'
  INTO RETURNED-MESSAGE.
  GOBACK.
